import React, { useState, useEffect } from 'react';
import { ChevronLeft } from 'lucide-react';
import './OrderForm.css';

interface Order {
  id?: number;
  trackingNumber?: string;
  senderName?: string;
  receiverName: string;
  phoneNumber: string;
  address: string;
  city: string;
  weightKg: number;
  codAmount?: number;
  isFragile: boolean;
  items: string;
  status?: string;
  createdAt?: string;
}

interface OrderFormProps {
  initialData?: Order;
  onSubmit: (data: Order) => Promise<void>;
  onCancel: () => void;
  isLoading: boolean;
  isEditing: boolean;
  autoGeneratedOrderId?: string;
  currentStatus?: string;
}

const OrderForm: React.FC<OrderFormProps> = ({
  initialData,
  onSubmit,
  onCancel,
  isLoading,
  isEditing,
  autoGeneratedOrderId,
  currentStatus
}) => {
  const [formData, setFormData] = useState<Order>(
    initialData || {
      senderName: '',
      receiverName: '',
      phoneNumber: '',
      address: '',
      city: '',
      weightKg: 1,
      items: '1',
      isFragile: false,
      codAmount: 0
    }
  );

  const [errors, setErrors] = useState<{ [key: string]: string }>({});

  useEffect(() => {
    if (initialData) {
      setFormData(initialData);
    }
  }, [initialData]);

  const validateForm = (): boolean => {
    const newErrors: { [key: string]: string } = {};

    if (!formData.senderName?.trim()) {
      newErrors.senderName = 'Sender name is required';
    }

    if (!formData.receiverName?.trim()) {
      newErrors.receiverName = 'Recipient name is required';
    }

    const phoneRegex = /^(?:\+92|0)[0-9]{10}$/;
    if (!phoneRegex.test(formData.phoneNumber.replace(/\s+/g, ''))) {
      newErrors.phoneNumber = 'Invalid phone number (use 03001234567 format)';
    }

    if (!formData.address?.trim() || formData.address.trim().length < 5) {
      newErrors.address = 'Address must be at least 5 characters';
    }

    if (!formData.city?.trim()) {
      newErrors.city = 'City is required';
    }

    if (!formData.weightKg || formData.weightKg <= 0 || formData.weightKg > 1000) {
      newErrors.weightKg = 'Weight must be between 0 and 1000 kg';
    }

    if (!formData.items?.trim()) {
      newErrors.items = 'Item names are required';
    }

    if (formData.codAmount && formData.codAmount < 0) {
      newErrors.codAmount = 'Amount cannot be negative';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>
  ) => {
    const { name, value, type } = e.target;

    if (type === 'checkbox') {
      const checked = (e.target as HTMLInputElement).checked;
      setFormData((prev) => ({
        ...prev,
        [name]: checked
      }));
    } else {
      setFormData((prev) => ({
        ...prev,
        [name]: value
      }));
    }

    if (errors[name]) {
      setErrors((prev) => {
        const newErrors = { ...prev };
        delete newErrors[name];
        return newErrors;
      });
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!validateForm()) {
      return;
    }

    try {
      await onSubmit(formData);
    } catch (error) {
      console.error('Form submission error:', error);
    }
  };

  return (
    <div className="order-form-container">
      <div className="form-header">
        <button className="back-btn" onClick={onCancel} type="button">
          <ChevronLeft size={20} />
          Back
        </button>
        <div className="form-title-section">
          <h1>{isEditing ? 'Modify Order Entry' : 'Create a New Order Entry'}</h1>
          <p>
            {isEditing
              ? 'Make changes to existing order or cancel to return back to orders page.'
              : 'Create a new order manually to be added amongst your existing orders or cancel to return back to orders page.'}
          </p>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="order-form">
        <div className="form-top-section">
          <div className="order-id-section">
            <div className="order-id-info">
              <label>Order Number:</label>
              <span className="order-id-value">
                {formData.trackingNumber || autoGeneratedOrderId || 'SWF-00000'}
              </span>
            </div>
            {currentStatus && (
              <div className="status-section">
                <label>Current Status:</label>
                <span className={`status-badge status-${currentStatus.toLowerCase()}`}>
                  {currentStatus.split('_').join(' ')}
                </span>
              </div>
            )}
          </div>
        </div>

        <div className="form-columns">
          <div className="form-column left">
            <div className="form-group">
              <label htmlFor="receiverName" className="required">
                Recipient Name
              </label>
              <input
                type="text"
                id="receiverName"
                name="receiverName"
                value={formData.receiverName}
                onChange={handleChange}
                placeholder="Recipient Name"
                className={errors.receiverName ? 'error' : ''}
              />
              {errors.receiverName && (
                <span className="error-message">{errors.receiverName}</span>
              )}
            </div>

            <div className="form-group">
              <label htmlFor="city" className="required">
                City
              </label>
              <input
                type="text"
                id="city"
                name="city"
                value={formData.city}
                onChange={handleChange}
                placeholder="City"
                className={errors.city ? 'error' : ''}
              />
              {errors.city && <span className="error-message">{errors.city}</span>}
            </div>

            <div className="form-group">
              <label htmlFor="address" className="required">
                Address
              </label>
              <textarea
                id="address"
                name="address"
                value={formData.address}
                onChange={handleChange}
                placeholder="Address"
                rows={3}
                className={errors.address ? 'error' : ''}
              />
              {errors.address && <span className="error-message">{errors.address}</span>}
            </div>

            <div className="form-group">
              <label htmlFor="codAmount">Amount</label>
              <input
                type="number"
                id="codAmount"
                name="codAmount"
                value={formData.codAmount || ''}
                onChange={handleChange}
                placeholder="Amount"
                step="0.01"
                min="0"
                className={errors.codAmount ? 'error' : ''}
              />
              {errors.codAmount && (
                <span className="error-message">{errors.codAmount}</span>
              )}
            </div>

            <div className="form-group">
              <label htmlFor="phoneNumber" className="required">
                Phone Number
              </label>
              <input
                type="tel"
                id="phoneNumber"
                name="phoneNumber"
                value={formData.phoneNumber}
                onChange={handleChange}
                placeholder="Phone Number"
                className={errors.phoneNumber ? 'error' : ''}
              />
              {errors.phoneNumber && (
                <span className="error-message">{errors.phoneNumber}</span>
              )}
            </div>
          </div>

          <div className="form-column right">
            <div className="form-group">
              <label htmlFor="senderName" className="required">
                Sender Name
              </label>
              <input
                type="text"
                id="senderName"
                name="senderName"
                value={formData.senderName}
                onChange={handleChange}
                placeholder="Sender Name"
                className={errors.senderName ? 'error' : ''}
              />
              {errors.senderName && (
                <span className="error-message">{errors.senderName}</span>
              )}
            </div>

            <div className="form-group">
              <label htmlFor="weightKg" className="required">
                Weight (kg)
              </label>
              <input
                type="number"
                id="weightKg"
                name="weightKg"
                value={formData.weightKg}
                onChange={handleChange}
                placeholder="Weight (kg)"
                step="0.01"
                min="0.01"
                max="1000"
                className={errors.weightKg ? 'error' : ''}
              />
              {errors.weightKg && (
                <span className="error-message">{errors.weightKg}</span>
              )}
            </div>

            <div className="form-group">
              <label htmlFor="items" className="required">
                Item Names
              </label>
              <input
                type="text"
                id="items"
                name="items"
                value={formData.items}
                onChange={handleChange}
                placeholder="e.g. Jeans, Shirt, Jacket"
                className={errors.items ? 'error' : ''}
              />
              {errors.items && <span className="error-message">{errors.items}</span>}
            </div>

            <div className="form-group">
              <label htmlFor="createdAt">Date</label>
              <input
                type="date"
                id="createdAt"
                value={
                  formData.createdAt
                    ? formData.createdAt.split('T')[0]
                    : new Date().toISOString().split('T')[0]
                }
                disabled
              />
            </div>

            <div className="form-group toggle-group">
              <label htmlFor="isFragile">Fragile</label>
              <label className="toggle-label">
                <input
                  type="checkbox"
                  id="isFragile"
                  name="isFragile"
                  checked={formData.isFragile}
                  onChange={handleChange}
                  className="toggle-input"
                />
                <span className="toggle-switch"></span>
              </label>
            </div>
          </div>
        </div>

        <div className="form-footer">
          <button
            type="button"
            className="btn btn-cancel"
            onClick={onCancel}
            disabled={isLoading}
          >
            Cancel
          </button>
          <button
            type="submit"
            className="btn btn-submit"
            disabled={isLoading}
          >
            {isLoading ? 'Saving...' : 'Save Changes'}
          </button>
        </div>
      </form>
    </div>
  );
};

export default OrderForm;
